// AngularjsQuickStart/Web-CLI/src/app/Login/login.component.ts
import {Component,Injectable } from '@angular/core';
import {RouterModule,ActivatedRoute,Router} from '@angular/router';
import {AuthenticateService} from "../appglobal/authenticate.service";
import {LoginUser} from "../appglobal/loginUser";
import {LoginForm} from "./loginForm";

@Component({
    selector:'login',
    templateUrl:'login.component.html',
})

@Injectable()
export class LoginComponent {
  loginUser:LoginUser;
  loginForm:LoginForm={Email:"test@test.com",Password:"Password1"};
  constructor(
    private router:Router,
    private authService:AuthenticateService,

  ){}


  login(loginCommand):void{
      let command={
        username:loginCommand.Email,
        password:loginCommand.Password,
      };
    this.authService.login(command).then(response=>this.loginSuccess(response));
  }

  loginSuccess(response){
    console.log(response.json());
  }
}




<!--[hidden]="!IsLogin"-->
<div class="container" >

  <form #loginForm="ngForm" class="form-signin" style="max-width: 330px;padding: 15px;margin: 0 auto;">
    <h2 class="form-signin-heading">Please sign in</h2>

    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" name="email"  [(ngModel)]="loginForm.Email"  class="form-control" placeholder="Email address" required="" autofocus="">
    TODO: remove this: {{loginForm.Email}}
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" [(ngModel)]="loginForm.Password" class="form-control" placeholder="Password" required="">

    <div class="checkbox">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>

    <button class="btn btn-lg btn-primary btn-block" type="submit" (click)="login(loginForm)">Sign in</button>
  </form>
</div>

// AngularjsQuickStart/VueQS/hello-world/src/components/Login.vue
<template>
  <form class="form-signin logincss">
  <img class="mb-4" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
  
  <label for="inputEmail" class="sr-only">Email address</label>
  <input type="email" v-model="UserName" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">

  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password" v-model="Password" id="inputPassword" class="form-control" placeholder="Password" required="">
  
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button @click="login" class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-muted">© 2017-2019</p>
</form>
</template>

<script>
export default {
  name: 'Login',
  data:function(){
    return {
      UserName:'',
      Password:'',
    }
  },
  methods:{
    login:function(){
      this.$axios.post(this.$baseUrl+"api/User/authenticate", {
        UserName: this.UserName,
        Password: this.Password
      })
      .then(function (response) {
        console.log(response);
      })
      .catch(function (error) {
        console.log(error);
      });
       this.$router.push('/main');
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

.logincss{
  width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
}

</style>
